### ISSUE TITLE
Missing info property in EpisodeData

### ISSUE THREAD

**Issue by ItaiBear** [Farama-Foundation/Minari#125]
### Missing info property in EpisodeData

The DataCollectorV0 wrapper can optionally record the info from each step. However, when creating a dataset from the collector the info data is lost. 
Shouldn't EpisodeData also optionally keep the infos? Else, what is the purpose of recording the info on the wrapper?

**Comment by balisujohn** [comment]
Thanks for your report. We are aware of this are planning to fix it and release official info standards in (likely) the next release. Essentially, our first party datasets have fields, but because h5py doesn't support arbitrary python objects, some work needs to be done to actually define our standards for what infos can be saved and how to save them when creating a new dataset and similarly how to retrieve them.
