### ISSUE TITLE
[Proposal] Porting Antmazes to Minari.

### ISSUE THREAD

**Issue by RajGhugare19** [Farama-Foundation/Minari#152]
### Proposal

I think it would be a great idea to port [Antmaze](https://robotics.farama.org/envs/maze/ant_maze/) data originally proposed in D4RL, to Minari. 

### Motivation

Many offline RL papers use antmaze. Many papers will even skip pointmaze and only report numbers on antmaze because the latter is more difficult. I think adding this dataset and environment with Minari's clean and easier to use code will boost Minari's usage amongst offline RL researchers.

### Pitch

1) Use the data collecting policy from D4RL to re-collect data in Minari. I don't think the policy can be used directly, because the ant model for the original D4RL (mujoco-py antmaze) was different. I found that you could just divide the control output of the D4RL data collecting policy by some constant factor (like 5 / 10), it seems to work on gymansium antmaze. 
2) If point (1)' fix is not appropriate, we would need to train a new data collecting policy for the antmaze and use it to collect new data.

### Checklist

- [ YES ] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by skylooop** [comment]
Upvotting your proposal. Minari list remote shows that there are several ant maze datasets. However, seems like they are not the same as in d4rl, or I'm missing something?

**Comment by rodrigodelazcano** [comment]
Hey @RajGhugare19, as @skylooop mentioned we have uploaded datasets for AntMaze but it won't show up in the docs until we merge this PR: https://github.com/Farama-Foundation/Minari/pull/155

Our approach for generating the datasets has been number 2. We decided to train our own goal reaching policy for the ant since we found that the d4rl policy didn't perform very well in our environment. Also, when replaying the d4rl datasets the ant's behavior is not very reliable as for what it is stated in the paper. I haven't tried dividing the control output though...

Any way, our new datasets achieve a success rate greater than 85% for all of the trajectories in every ant dataset. We've tried to resemble the data collection process as much as possible to the original in d4rl. You can have a look at the scripts here: https://github.com/rodrigodelazcano/d4rl-minari-dataset-generation/blob/main/scripts/antmaze/create_antmaze_dataset.py

We still have to add more documentation to the scripts for reproducibility. In the meantime let us know if you have anymore questions, I'll be happy to answer them :)

**Comment by RajGhugare19** [comment]
Thanks for your reply!

**Comment by perrin-isir** [comment]
Hi, with the current Minari antmaze datasets (mostly medium and large), I haven't been able to successfully perform offline RL with algorithms like IQL that succeed on D4RL antmazes. Is this a known issue? Has someone been able to solve the Minari antmazes based on the Minari datasets with standard offline RL algorithms? 
I tried to remove the final still transitions that only accumulate reward, or to use the recommended trick in D4RL to subtract 1 to the reward, but this only led to very limited success.

**Comment by younik** [comment]
> Hi, with the current Minari antmaze datasets (mostly medium and large), I haven't been able to successfully perform offline RL with algorithms like IQL that succeed on D4RL antmazes. Is this a known issue? Has someone been able to solve the Minari antmazes based on the Minari datasets with standard offline RL algorithms? I tried to remove the final still transitions that only accumulate reward, or to use the recommended trick in D4RL to subtract 1 to the reward, but this only led to very limited success.

Hi @perrin-isir, 
We found a reproducibility issue with different versions of MuJoCo.
Can you try using the mujoco version pinned in requirements metadata of the dataset? 
```
'gymnasium-robotics>=1.2.3', 'mujoco>=3.1.1,<=3.1.6'
```

As a test, you should able to successfully replicate a rollout in the dataset

**Comment by perrin-isir** [comment]
Hi @younik , thank you for your quick answer. 
I downgraded mujoco (v3.1.6) (with gymnasium_robotics v1.3.1), but it did not improve the results of offline RL. Results are not zero, so the ant is able to walk towards very simple targets in some cases, but in D4RL the results would typically be much better. Isn't there also an issue with the dataset size, since among the 1000 episodes, many episodes reach the target after 200/300 steps, and the rest is an accumulation of the reward by staying still, so that makes a total of ~250k useful transitions out of the million in the dataset. Any known issue related to that?

**Comment by younik** [comment]
> Hi [@younik](https://github.com/younik) , thank you for your quick answer. I downgraded mujoco (v3.1.6) (with gymnasium_robotics v1.3.1), but it did not improve the results of offline RL. Results are not zero, so the ant is able to walk towards very simple targets in some cases, but in D4RL the results would typically be much better. Isn't there also an issue with the dataset size, since among the 1000 episodes, many episodes reach the target after 200/300 steps, and the rest is an accumulation of the reward by staying still, so that makes a total of ~250k useful transitions out of the million in the dataset. Any known issue related to that?
> 
> PS: I should add that with the simpler D4RL/antmaze/umaze-v1, offline RL is successful.

I was not aware of this (cc @alexdavey), is this different in D4RL?
It is worth opening a new issue on this btw
