### ISSUE TITLE
[Bug Report] Incorrect observation shape in some antmaze-umaze-v0 episodes

### ISSUE THREAD

**Issue by cpnota** [Farama-Foundation/Minari#199]
**Describe the bug**
According to the documentation, the shape of the observation should be num_steps + 1. However, for a handful of episodes, the length is num_steps.

**Code example**

```python
import minari

dataset = minari.load_dataset("antmaze-umaze-v0", download=True)

for episode_data in dataset.iterate_episodes():
    if episode_data.observations["observation"].shape[0] == episode_data.total_timesteps:
        print("Warning: bad episode")
```

Output:
```
Warning: bad episode
Warning: bad episode
Warning: bad episode
Warning: bad episode
```

**System Info**
Describe the characteristic of your environment:
 * Installed via PIP
 * Operating system: Ubuntu 20.04.6 LTS
 * Python version: 3.8

**Additional context**
I haven't checked the other Ant environments.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/Farama-Foundation/Minari/issues) in the repo (**required**)

**Comment by alexdavey** [comment]
Thank you for spotting this! It appears that there was an issue with the DataCollector code that was used to generate this dataset.

In addition, there seems to be an issue with the episode/goal not being reset when the Ant has reached it. I am currently working on a new version of the antmaze datasets to fix these issues.

**Comment by alexdavey** [comment]
A new `v1` version of the antmaze datasets (e.g. `"antmaze-umaze-v1"`) has been released to fix this issue.

The new datasets are otherwise statistically very similar to the old `v0` datasets, so should be a drop-in replacement for most purposes. See [here](https://github.com/rodrigodelazcano/d4rl-minari-dataset-generation/pull/13) for a comparison with the previous version.
