### ISSUE TITLE
Add tests for MinariDataset

### ISSUE THREAD

**Issue by younik** [Farama-Foundation/Minari#89]
Tests for the file [minari_dataset](https://github.com/Farama-Foundation/Minari/blob/main/minari/dataset/minari_dataset.py) should be added.

**Comment by Aaisha-Rani** [comment]
Is anyone working on this issue.

**Comment by Aaisha-Rani** [comment]
@younik .Yes. I would very much like to contribute to it. And some guidence is deeply appreciated

**Comment by younik** [comment]
If you check this file: https://github.com/Farama-Foundation/Minari/blob/main/tests/dataset/test_minari_dataset.py only the `__repr__` function of `EpisodeData` is checked.
However, we need at least a test for every function contained here: https://github.com/Farama-Foundation/Minari/blob/main/minari/dataset/minari_dataset.py

**Comment by Aaisha-Rani** [comment]
@younik  thank you for guidence

**Comment by younik** [comment]
@Aaisha-Rani we need this to be done soon.
If you already work on it, can you open a PR? If not, just let me know that I will take care of it

**Comment by Aaisha-Rani** [comment]
@younik . I am really sorry for the delay. But I am having a bit of difficulty understanding the code base. if you could guide me a little bit.

**Comment by balisujohn** [comment]
@Aaisha-Rani We unexpectedly had another task come up which depends on this task being completed very quickly, so if it's OK with you we can assign you a new task, since we have plenty of tasks available. Let me know if that sounds OK, and I'll create an issue describing the new task and assign you to it. Feel free to join the Farama [discord](https://discord.gg/bnJ6kubTg6) if you want to ask questions about the codebase; you can ask in the minari channel. The doc is available here and might also be useful: https://minari.farama.org/main/.

**Comment by Aaisha-Rani** [comment]
@balisujohn Thank you very much for help. Please assign me a new task. I have joined farma discord. And thankyou for providing the docs. I am new to open source contribution. So please assign task accordingly. And once again thank you very much for help.
